#!/usr/bin/env node
/**
 * Assemble the installable (PWA) build of an app.
 *
 *   node apps/build-pwa.mjs contractor-estimator
 *   node apps/build-pwa.mjs field-log
 *   node apps/build-pwa.mjs all
 *
 * index.html stays the source of truth and stays standalone — it still opens by
 * double-clicking it off a USB stick. This produces the *hosted* variant, which
 * is the same page plus the three things a browser needs before it will let
 * someone install it: a manifest, an icon set, and a service worker.
 *
 * A service worker cannot be inlined; it needs its own URL and its own scope.
 * That is the one reason the installable build is a folder rather than a file.
 *
 * Output goes to dist-pwa/<app>/ and is not committed.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

const APPS = {
  "contractor-estimator": {
    name: "Contractor Estimator",
    short: "Estimator",
    description:
      "Price site work off your own equipment and labour costs, take off dirt and rock, cruise timber, and print a client-ready quote. Works with no signal.",
  },
  "field-log": {
    name: "Field Log",
    short: "Field Log",
    description:
      "Daily field logs with crew and equipment hours, delays and standby, plus custom safety sheets you build and sign. Works with no signal.",
  },
};

const THEME = "#16301F";     // hunter deep — matches the app chrome
const BACKGROUND = "#FBFAF8"; // warm white — matches the canvas
const ICONS = ["apple-touch-icon.png", "icon-192.png", "icon-512.png", "icon-1024.png"];

/* Head tags the hosted build needs and the standalone file does not. */
const headTags = `
<link rel="icon" href="icons/icon-192.png" />
<link rel="manifest" href="manifest.webmanifest" />
<meta name="theme-color" content="${THEME}" />
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="mobile-web-app-capable" content="yes" />`;

/* Registration plus the iOS install hint. iOS gives no install prompt of its
   own, so without a nudge nobody ever finds Add to Home Screen. */
const bootScript = (appName) => `
<script>
(function () {
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function () {
      navigator.serviceWorker.register("sw.js").catch(function () { /* offline install is a bonus, not a requirement */ });
    });
  }

  // Standalone launches already live on the home screen — nothing to suggest.
  var standalone = window.matchMedia("(display-mode: standalone)").matches || window.navigator.standalone === true;
  var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
  var dismissed = false;
  try { dismissed = localStorage.getItem("a2hs-dismissed") === "1"; } catch (e) {}

  if (iOS && !standalone && !dismissed) {
    window.addEventListener("load", function () {
      var bar = document.createElement("div");
      bar.setAttribute("role", "note");
      bar.style.cssText = "position:fixed;left:12px;right:12px;bottom:12px;z-index:9999;" +
        "display:flex;gap:12px;align-items:center;padding:12px 14px;border-radius:16px;" +
        "background:${THEME};color:#fff;font:400 13px/1.45 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;" +
        "box-shadow:0 8px 30px rgba(0,0,0,.28)";
      bar.innerHTML = '<span style="flex:1">Add <strong>${appName}</strong> to your home screen: tap Share, then <strong>Add to Home Screen</strong>.</span>' +
        '<button type="button" style="appearance:none;border:0;background:rgba(255,255,255,.16);color:#fff;' +
        'border-radius:10px;padding:8px 12px;font:inherit;font-weight:600;cursor:pointer">Got it</button>';
      bar.querySelector("button").addEventListener("click", function () {
        try { localStorage.setItem("a2hs-dismissed", "1"); } catch (e) {}
        bar.remove();
      });
      document.body.appendChild(bar);
    });
  }
})();
</script>`;

/* Safe-area padding: in standalone mode on a notched phone the sticky header
   would otherwise sit under the status bar. */
const safeAreaCss = `
<style>
@media (display-mode: standalone) {
  .chrome { padding-top: env(safe-area-inset-top, 0px); }
  body { padding-bottom: env(safe-area-inset-bottom, 0px); }
}
</style>`;

function serviceWorker(version, assets) {
  return `/* Generated by apps/build-pwa.mjs — do not edit by hand. */
const CACHE = "app-${version}";
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Cache first, because the whole point is that it works with no signal. The
   network copy is fetched in the background and replaces the cached one, so a
   new version lands on the next launch rather than never. */
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;

  event.respondWith(
    caches.match(req).then((hit) => {
      const fresh = fetch(req)
        .then((res) => {
          if (res && res.status === 200) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => hit);
      return hit || fresh;
    })
  );
});
`;
}

function build(slug) {
  const meta = APPS[slug];
  if (!meta) throw new Error(`Unknown app "${slug}". Known: ${Object.keys(APPS).join(", ")}`);

  const appDir = resolve(here, slug);
  const srcPath = resolve(appDir, "index.html");
  const outDir = resolve(here, "dist-pwa", slug);

  let html = readFileSync(srcPath, "utf8");
  if (!html.includes("</head>")) throw new Error(`${slug}: no </head> to inject into`);
  html = html.replace("</head>", `${headTags}\n${safeAreaCss}\n</head>`);
  html = html.replace("</body>", `${bootScript(meta.name)}\n</body>`);

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(resolve(outDir, "icons"), { recursive: true });

  writeFileSync(resolve(outDir, "index.html"), html);

  const manifest = {
    name: meta.name,
    short_name: meta.short,
    description: meta.description,
    start_url: "./index.html",
    scope: "./",
    display: "standalone",
    orientation: "any",
    theme_color: THEME,
    background_color: BACKGROUND,
    categories: ["business", "productivity", "utilities"],
    icons: [
      { src: "icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "icons/icon-1024.png", sizes: "1024x1024", type: "image/png", purpose: "any" },
    ],
  };
  writeFileSync(resolve(outDir, "manifest.webmanifest"), JSON.stringify(manifest, null, 2));

  for (const icon of ICONS) {
    const from = resolve(appDir, "icons", icon);
    if (!existsSync(from)) throw new Error(`${slug}: missing icon ${icon} — run node apps/make-icons.mjs`);
    copyFileSync(from, resolve(outDir, "icons", icon));
  }

  // Version the cache off the page itself, so a changed app busts it and an
  // unchanged one does not churn the user's storage.
  const version = createHash("sha256").update(html).digest("hex").slice(0, 12);
  const assets = ["./index.html", "./manifest.webmanifest", ...ICONS.map((i) => `./icons/${i}`)];
  writeFileSync(resolve(outDir, "sw.js"), serviceWorker(version, assets));

  const kb = (n) => (n / 1024).toFixed(1) + " KB";
  console.log(`${slug}: dist-pwa/${slug}/  (page ${kb(html.length)}, cache ${version})`);
}

const arg = process.argv[2] || "all";
(arg === "all" ? Object.keys(APPS) : [arg]).forEach(build);
